name: Assign Label on Merge

on:
  pull_request:
    types: [closed]

jobs:
  assign-label-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: 
      issues: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Assign Label to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['done']
            })

      - name: Remove 'development' Label from PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use the default GITHUB_TOKEN
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'development'
            })

      - name: Find Connected Issue
        id: find_issue
        run: |
          connected_issue=$(jq --raw-output '.pull_request.body' $GITHUB_EVENT_PATH | grep -o '#[0-9]\+' | head -n 1 | tr -d '#')
          echo "::set-output name=issue_number::${connected_issue}"
        if: github.event.pull_request.merged

      - name: Assign Label to Issue
        if: steps.find_issue.outputs.issue_number
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.find_issue.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['done']
            })

      - name: Remove 'development' Label from Issue
        if: steps.find_issue.outputs.issue_number
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: ${{ steps.find_issue.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'development'
            })
