- name: Assign Label to PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.CRM_PULL_REQUEST_TOKEN }}
          script: |
            const { data: labels } = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const existingLabels = labels.map(label => label.name);

            const newLabels = [...existingLabels, 'done'];

            await github.issues.setLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: newLabels
            });
