name: Assign Label on Merge

on:
  pull_request:
    types: [closed]

jobs:
  assign-label-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: 
      issues: write 

    steps:
      - name: Check out the code
        uses: actions/checkout@v4 # Updated to v4

      - name: Assign Label to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['done']
            })

      - name: Find Connected Issue
        id: find_issue
        run: |
          if [[ "$GITHUB_EVENT_PATH" == *".json" ]]; then
            echo "::set-output name=issue_number::$(jq --raw-output .issue.number $GITHUB_EVENT_PATH)"
          fi
        if: github.event.pull_request.merged && github.event.pull_request.head.repo != github.event.pull_request.base.repo

      - name: Assign Label to Issue
        if: steps.find_issue.outputs.issue_number
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.find_issue.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['done']
            })
